server:
  port: 9003
spring:
  application:
    name: tensquare-qa #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/tensquare_qa?useSSl=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true

    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true

jwt:
  config:
    key: heyufei