server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/ #eureka客户端和服务器端交互的地址,6868是eureka服务的地址
  instance:
    prefer-ip-address: true  #能否跨服务器访问（就是说访问另一个服务）

spring:
  application:
    name: hyf-spit #指定服务名
  data:
    mongodb:
      #uri: mongodb://120.24.145.157:27017/?compressors=disabled&gssapiServiceName=mongodb
      host: 120.24.145.157
      database: hyf_spit
      username: root
      password: Jsu123456.
      port: 27017

  redis:
    host: 120.24.145.157
    password: Jsu123456.
    port: 6379

jwt:
  config:
    key: heyufei
    ttl: 360000000000