server:
  port: 9008
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/ #eureka客户端和服务器端交互的地址,6868是eureka服务的地址
  instance:
    prefer-ip-address: true  #能否跨服务器访问（就是说访问另一个服务）

spring:
  application:
    name: hyf-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.145.157:3306/tensquare_user?useSSl=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Jsu123456.
  jpa:
    database: MySQL
    show-sql: true

    properties:
      hibernate:
        globally_quoted_identifiers: true

  redis:
    host: localhost

  rabbitmq:
    host: localhost
jwt:
  config:
    key: heyufei
    ttl: 360000000000
