server:
  port: 12000

spring:
  application:
    name: heyufei‐config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/h243582/My-All-Config.git
          #https://gitee.com/chuanzhiliubei/tensquare‐config.git
