server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_gathering?useSSl=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true

    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true

    properties:
      hibernate:
        globally_quoted_identifiers: true

  redis:
    host: localhost
    port: 6379
